### ISSUE TITLE
Great work, I'd glad to contribute to the Deep Learning Deck

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [taivop/anki-decks#1]
I'm a big fan of recall learning after having read different studies and [A mind for numbers](https://www.amazon.com/Mind-Numbers-Science-Flunked-Algebra/dp/039916524X/ref=sr_1_1?ie=UTF8&qid=1498573315&sr=8-1&keywords=a+mind+for+numbers&tag=kasbl023-20) and [Make ist stick](https://www.amazon.com/Make-Stick-Science-Successful-Learning/dp/0674729013/ref=sr_1_1?ie=UTF8&qid=1498573349&sr=8-1&keywords=make+it+stick&tag=kasbl023-20). I'd be glad to contribute to the Deep Learning Deck once I finish my degree in DL. 
Cheers!

**Comment by taivop** [comment]
Hey, the deep learning deck is specifically for a course at ETH Zürich so I think you'll find it easier to take just a few cards from my deck).

Also, are you aware of the shared decks at https://ankiweb.net/shared/decks/ ?

**Comment by taivop** [comment]
Closing as this seems to not be relevant any more.
