### ISSUE TITLE
Remove scheduling or convert to V2

### ISSUE THREAD

**Issue by AdrienLemaire** [taivop/anki-decks#2]
Hi, I found your repo from [awesome-anki](https://github.com/tianshanghong/awesome-anki#themes).
I tried to import a deck, but got the error `Exception: V2 scheduler can not import V1 decks with scheduling included.`. 

Can you either remove scheduling or add a v2 scheduler apkg version? Or do you have a better suggestion?

**Comment by sandersantema** [comment]
I had the same problem, but there's an easy fix. Make a new profile, which will have the V2 scheduler disabled by default and export a version without scheduling content from there. Switch back to your V2 scheduler profile and import the generated .apkg file.

**Comment by sandersantema** [comment]
Or if you'd want you can use this one which I exported: 
[How-to-Formulate-Knowledge.apkg.zip](https://github.com/taivop/anki-decks/files/3252081/How-to-Formulate-Knowledge.apkg.zip)

I'd gladly take this version down @taivop if you're not okay with it.

**Comment by taivop** [comment]
Thanks for the report and file, updated the binary!
